# Generated by Django 4.2.9 on 2025-06-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_company_delete_stockdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-date', 'company_name']},
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['company_name', 'date'], name='bands_compa_company_2cb1e1_idx'),
        ),
    ]
